### 로그인
POST http://localhost:1882/api/auth/login
Content-Type: application/json

{
    "homepageId": "manyman",
    "password":"1234"
}


### 임시회원 등록 (JSON)
POST http://localhost:1882/api/auth/regist
Content-Type: application/json

{
    "homepageId": "manyman",
    "password":"1234",
    "name":"기성",
    "email":"ideakslee2@gmail.com",
    "phone":"02-864-7576",
    "mphone":"010-4033-7572",
    "company":"아이디어스"
}


### 아이디체크
POST http://localhost:1882/api/auth/idcheck
Content-Type: application/json

{
    "homepageId": "3333"
}

### 아이디찾기
POST http://localhost:1882/api/auth/idpassfind
Content-Type: application/json

{
    "idOrPass": "id",
    "email": "ideakslee@gmail.com",
    "mphone": "010-4033-7576"
}

### 비밀번호찾기
POST http://localhost:1882/api/auth/idpassfind
Content-Type: application/json

{
    "idOrPass": "password",
    "homepageId": "3333",
    "email": "ideakslee@gmail.com",
    "mphone": "010-4033-7576"
}

### 구글 OAuth 코드 교환 (임시코드 → accessToken)
POST http://localhost:1882/api/auth/oauth2/exchange?code=b8b21b2e6dbafe2de6332818c0294e7
Content-Type: application/x-www-form-urlencoded
